---
title: "Assignment 7"
author: "Mohit Ghodake"
date: "April 18, 2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(magrittr)
library(Metrics)
library(plotly)
library(corrplot)
library(PerformanceAnalytics)
library(Hmisc)
library(knitr)
library(mctest)
library(caret)
library(ROCR)
library(scales)
library(dummies)
library(neuralnet)
library(class)
library(dplyr)
library(e1071)
library(tree)
library(ISLR)
library(data.table)
library(arules)
library(arulesViz)

df <- fread("Credit.csv")

df$AMOUNT_REQUESTED <- as.numeric(gsub(",","",df$AMOUNT_REQUESTED))
df$CREDIT_EXTENDED <- NULL
df$`OBS#` <- NULL
```


```{r, echo = TRUE}
##################
#1
#Creating Dummy Varaibles
df$CHK0 <- factor(ifelse(df$CHK_ACCT == 0, 1, 0))
df$CHK1 <- factor(ifelse(df$CHK_ACCT == 1, 1, 0))
df$CHK2 <- factor(ifelse(df$CHK_ACCT == 2, 1, 0))
df$CHK3 <- factor(ifelse(df$CHK_ACCT == 3, 1, 0))

df$SAV0 <- factor(ifelse(df$SAV_ACCT == 0, 1, 0))
df$SAV1 <- factor(ifelse(df$SAV_ACCT == 1, 1, 0))
df$SAV2 <- factor(ifelse(df$SAV_ACCT == 2, 1, 0))
df$SAV3 <- factor(ifelse(df$SAV_ACCT == 3, 1, 0))
df$SAV4 <- factor(ifelse(df$SAV_ACCT == 4, 1, 0))

df$HISTORY0 <- factor(ifelse(df$HISTORY == 0, 1, 0))
df$HISTORY1 <- factor(ifelse(df$HISTORY == 1, 1, 0))
df$HISTORY2 <- factor(ifelse(df$HISTORY == 2, 1, 0))
df$HISTORY3 <- factor(ifelse(df$HISTORY == 3, 1, 0))
df$HISTORY4 <- factor(ifelse(df$HISTORY == 4, 1, 0))

df$JOB0 <- factor(ifelse(df$JOB == 0, 1, 0))
df$JOB1 <- factor(ifelse(df$JOB == 1, 1, 0))
df$JOB2 <- factor(ifelse(df$JOB == 2, 1, 0))
df$JOB3 <- factor(ifelse(df$JOB == 3, 1, 0))

df$TYPE0 <- factor(ifelse(df$TYPE == 0, 1, 0))
df$TYPE1 <- factor(ifelse(df$TYPE == 1, 1, 0))
df$TYPE2 <- factor(ifelse(df$TYPE == 2, 1, 0))
df$TYPE3 <- factor(ifelse(df$TYPE == 3, 1, 0))
df$TYPE4 <- factor(ifelse(df$TYPE == 4, 1, 0))
df$TYPE5 <- factor(ifelse(df$TYPE == 5, 1, 0))
df$TYPE6 <- factor(ifelse(df$TYPE == 6, 1, 0))

df$CHK_ACCT <- NULL
df$SAV_ACCT <- NULL
df$HISTORY <- NULL
df$JOB <- NULL
df$TYPE <- NULL
```


```{r, echo = TRUE}
#########################
#2
set.seed(12345)
df$PROFITABLE <- ifelse(df$NPV > 0, 1, 0)
df$PROFITABLE <- factor(df$PROFITABLE)
df1 <- df[, -16]
df1 <- df1[, -41]
#df1 <- scale(df1)

kmeansCluster = kmeans(df1, 5, nstart=20)
kmeansCluster
dist(kmeansCluster$centers)
```


```{r, echo = TRUE}
########################
#4
newdf <- data.frame(df$NPV, kmeansCluster$cluster)
cluster1_count = 0
cluster2_count = 0
cluster3_count = 0
cluster4_count = 0
cluster5_count = 0

profitable_cluster1_count = 0
profitable_cluster2_count = 0
profitable_cluster3_count = 0
profitable_cluster4_count = 0
profitable_cluster5_count = 0

NPV_1 = 0
NPV_2 = 0
NPV_3 = 0
NPV_4 = 0
NPV_5 = 0


for (i in 1:nrow(newdf)){
  if (newdf[i, 2] == 1){ 
    cluster1_count = cluster1_count + 1
    NPV_1 = NPV_1 + newdf[i, 1]
  }
  if (newdf[i, 2] == 2){ 
    cluster2_count = cluster2_count + 1
    NPV_2 = NPV_2 + newdf[i, 1]
  }
  if (newdf[i, 2] == 3){ 
    cluster3_count = cluster3_count + 1
    NPV_3 = NPV_3 + newdf[i, 1]
  }
  if (newdf[i, 2] == 4){ 
    cluster4_count = cluster4_count + 1
    NPV_4 = NPV_4 + newdf[i, 1]
  }
  if (newdf[i, 2] == 5){ 
    cluster5_count = cluster5_count + 1
    NPV_5 = NPV_5 + newdf[i, 1]
  }
}

avgNPV_1 <- NPV_1/cluster1_count
avgNPV_2 <- NPV_2/cluster2_count
avgNPV_3 <- NPV_3/cluster3_count
avgNPV_4 <- NPV_4/cluster4_count
avgNPV_5 <- NPV_5/cluster5_count

for (i in 1:nrow(newdf)){
  if (newdf[i, 2] == 1 & newdf[i, 1] > 0){ 
    profitable_cluster1_count = profitable_cluster1_count + 1
  }
  if (newdf[i, 2] == 2 & newdf[i, 1] > 0){ 
    profitable_cluster2_count = profitable_cluster2_count + 1
  }
  if (newdf[i, 2] == 3 & newdf[i, 1] > 0){ 
    profitable_cluster3_count = profitable_cluster3_count + 1
  }
  if (newdf[i, 2] == 4 & newdf[i, 1] > 0){ 
    profitable_cluster4_count = profitable_cluster4_count + 1
  }
  if (newdf[i, 2] == 5 & newdf[i, 1] > 0){ 
    profitable_cluster5_count = profitable_cluster5_count + 1
  }
}

percent_prof_1 <- profitable_cluster1_count/cluster1_count*100
percent_prof_2 <- profitable_cluster2_count/cluster2_count*100
percent_prof_3 <- profitable_cluster3_count/cluster3_count*100
percent_prof_4 <- profitable_cluster4_count/cluster4_count*100
percent_prof_5 <- profitable_cluster5_count/cluster5_count*100


Cluster <- c(1,
             2,
             3,
             4,
             5)

Count <- c(cluster1_count,
           cluster2_count,
           cluster3_count,
           cluster4_count,
           cluster5_count)

Profitable <- c(profitable_cluster1_count,
                profitable_cluster2_count,
                profitable_cluster3_count,
                profitable_cluster4_count,
                profitable_cluster5_count)

PercentProfitable <- c(percent_prof_1,
                       percent_prof_2,
                       percent_prof_3,
                       percent_prof_4,
                       percent_prof_5)

NPV <- c(NPV_1,
         NPV_2,
         NPV_3,
         NPV_4,
         NPV_5)

AVG_NPV <- c(avgNPV_1,
             avgNPV_2,
             avgNPV_3,
             avgNPV_4,
             avgNPV_5)

df_modified <- data.frame(Cluster, Count, Profitable, PercentProfitable, NPV, AVG_NPV)
df_modified

##
#4a
barplot(PercentProfitable, names.arg = Cluster, xlab = "Cluster", ylab = "Percent Profitability", col = "blue", main = "Profitability by Cluster")

##
#4b
df_modified
barplot(AVG_NPV, names.arg = Cluster, xlab = "Cluster", ylab = "Average NPV", col = "red", main = "Average NPV by Cluster")

```


```{r, echo = TRUE}
#######################
#6
kmeansCluster_4 = kmeans(df1, 4, nstart=20)
kmeansCluster_4
dist(kmeansCluster_4$centers)

newdf_1 <- data.frame(df$NPV, kmeansCluster_4$cluster)
cluster1_count = 0
cluster2_count = 0
cluster3_count = 0
cluster4_count = 0

profitable_cluster1_count = 0
profitable_cluster2_count = 0
profitable_cluster3_count = 0
profitable_cluster4_count = 0

NPV_1 = 0
NPV_2 = 0
NPV_3 = 0
NPV_4 = 0


for (i in 1:nrow(newdf_1)){
  if (newdf_1[i, 2] == 1){ 
    cluster1_count = cluster1_count + 1
    NPV_1 = NPV_1 + newdf_1[i, 1]
  }
  if (newdf_1[i, 2] == 2){ 
    cluster2_count = cluster2_count + 1
    NPV_2 = NPV_2 + newdf_1[i, 1]
  }
  if (newdf_1[i, 2] == 3){ 
    cluster3_count = cluster3_count + 1
    NPV_3 = NPV_3 + newdf_1[i, 1]
  }
  if (newdf_1[i, 2] == 4){ 
    cluster4_count = cluster4_count + 1
    NPV_4 = NPV_4 + newdf_1[i, 1]
  }
}

avgNPV_1 <- NPV_1/cluster1_count
avgNPV_2 <- NPV_2/cluster2_count
avgNPV_3 <- NPV_3/cluster3_count
avgNPV_4 <- NPV_4/cluster4_count

for (i in 1:nrow(newdf_1)){
  if (newdf_1[i, 2] == 1 & newdf_1[i, 1] > 0){ 
    profitable_cluster1_count = profitable_cluster1_count + 1
  }
  if (newdf_1[i, 2] == 2 & newdf_1[i, 1] > 0){ 
    profitable_cluster2_count = profitable_cluster2_count + 1
  }
  if (newdf_1[i, 2] == 3 & newdf_1[i, 1] > 0){ 
    profitable_cluster3_count = profitable_cluster3_count + 1
  }
  if (newdf_1[i, 2] == 4 & newdf_1[i, 1] > 0){ 
    profitable_cluster4_count = profitable_cluster4_count + 1
  }
}

percent_prof_1 <- profitable_cluster1_count/cluster1_count*100
percent_prof_2 <- profitable_cluster2_count/cluster2_count*100
percent_prof_3 <- profitable_cluster3_count/cluster3_count*100
percent_prof_4 <- profitable_cluster4_count/cluster4_count*100


Cluster <- c(1,
             2,
             3,
             4)

Count <- c(cluster1_count,
           cluster2_count,
           cluster3_count,
           cluster4_count)

Profitable <- c(profitable_cluster1_count,
                profitable_cluster2_count,
                profitable_cluster3_count,
                profitable_cluster4_count)

PercentProfitable <- c(percent_prof_1,
                       percent_prof_2,
                       percent_prof_3,
                       percent_prof_4)

NPV <- c(NPV_1,
         NPV_2,
         NPV_3,
         NPV_4)

AVG_NPV <- c(avgNPV_1,
             avgNPV_2,
             avgNPV_3,
             avgNPV_4)

df_modified <- data.frame(Cluster, Count, Profitable, PercentProfitable, NPV, AVG_NPV)
df_modified

####
barplot(PercentProfitable, names.arg = Cluster, xlab = "Cluster", ylab = "Percent Profitability", col = "blue", main = "Profitability by Cluster")

#####
df_modified
barplot(AVG_NPV, names.arg = Cluster, xlab = "Cluster", ylab = "Average NPV", col = "red", main = "Average NPV by Cluster")


#####################

kmeansCluster_6 = kmeans(df1, 6, nstart = 20)
kmeansCluster_6
dist(kmeansCluster_6$centers)


newdf_2 <- data.frame(df$NPV, kmeansCluster_6$cluster)
cluster1_count = 0
cluster2_count = 0
cluster3_count = 0
cluster4_count = 0
cluster5_count = 0
cluster6_count = 0

profitable_cluster1_count = 0
profitable_cluster2_count = 0
profitable_cluster3_count = 0
profitable_cluster4_count = 0
profitable_cluster5_count = 0
profitable_cluster6_count = 0

NPV_1 = 0
NPV_2 = 0
NPV_3 = 0
NPV_4 = 0
NPV_5 = 0
NPV_6 = 0


for (i in 1:nrow(newdf_2)){
  if (newdf_2[i, 2] == 1){ 
    cluster1_count = cluster1_count + 1
    NPV_1 = NPV_1 + newdf_2[i, 1]
  }
  if (newdf_2[i, 2] == 2){ 
    cluster2_count = cluster2_count + 1
    NPV_2 = NPV_2 + newdf_2[i, 1]
  }
  if (newdf_2[i, 2] == 3){ 
    cluster3_count = cluster3_count + 1
    NPV_3 = NPV_3 + newdf_2[i, 1]
  }
  if (newdf_2[i, 2] == 4){ 
    cluster4_count = cluster4_count + 1
    NPV_4 = NPV_4 + newdf_2[i, 1]
  }
  if (newdf_2[i, 2] == 5){ 
    cluster5_count = cluster5_count + 1
    NPV_5 = NPV_5 + newdf_2[i, 1]
  }
  if (newdf_2[i, 2] == 6){ 
    cluster6_count = cluster6_count + 1
    NPV_6 = NPV_6 + newdf_2[i, 1]
  }
}

avgNPV_1 <- NPV_1/cluster1_count
avgNPV_2 <- NPV_2/cluster2_count
avgNPV_3 <- NPV_3/cluster3_count
avgNPV_4 <- NPV_4/cluster4_count
avgNPV_5 <- NPV_5/cluster5_count
avgNPV_6 <- NPV_6/cluster6_count

for (i in 1:nrow(newdf_2)){
  if (newdf_2[i, 2] == 1 & newdf_2[i, 1] > 0){ 
    profitable_cluster1_count = profitable_cluster1_count + 1
  }
  if (newdf_2[i, 2] == 2 & newdf_2[i, 1] > 0){ 
    profitable_cluster2_count = profitable_cluster2_count + 1
  }
  if (newdf_2[i, 2] == 3 & newdf_2[i, 1] > 0){ 
    profitable_cluster3_count = profitable_cluster3_count + 1
  }
  if (newdf_2[i, 2] == 4 & newdf_2[i, 1] > 0){ 
    profitable_cluster4_count = profitable_cluster4_count + 1
  }
  if (newdf_2[i, 2] == 5 & newdf_2[i, 1] > 0){ 
    profitable_cluster5_count = profitable_cluster5_count + 1
  }
  if (newdf_2[i, 2] == 6 & newdf_2[i, 1] > 0){ 
    profitable_cluster6_count = profitable_cluster6_count + 1
  }
}

percent_prof_1 <- profitable_cluster1_count/cluster1_count*100
percent_prof_2 <- profitable_cluster2_count/cluster2_count*100
percent_prof_3 <- profitable_cluster3_count/cluster3_count*100
percent_prof_4 <- profitable_cluster4_count/cluster4_count*100
percent_prof_5 <- profitable_cluster5_count/cluster5_count*100
percent_prof_6 <- profitable_cluster6_count/cluster6_count*100


Cluster <- c(1,
             2,
             3,
             4,
             5,
             6)

Count <- c(cluster1_count,
           cluster2_count,
           cluster3_count,
           cluster4_count,
           cluster5_count,
           cluster6_count)

Profitable <- c(profitable_cluster1_count,
                profitable_cluster2_count,
                profitable_cluster3_count,
                profitable_cluster4_count,
                profitable_cluster5_count,
                profitable_cluster6_count)

PercentProfitable <- c(percent_prof_1,
                       percent_prof_2,
                       percent_prof_3,
                       percent_prof_4,
                       percent_prof_5,
                       percent_prof_6)

NPV <- c(NPV_1,
         NPV_2,
         NPV_3,
         NPV_4,
         NPV_5,
         NPV_6)

AVG_NPV <- c(avgNPV_1,
             avgNPV_2,
             avgNPV_3,
             avgNPV_4,
             avgNPV_5,
             avgNPV_6)

df_modified <- data.frame(Cluster, Count, Profitable, PercentProfitable, NPV, AVG_NPV)
df_modified

####
barplot(PercentProfitable, names.arg = Cluster, xlab = "Cluster", ylab = "Percent Profitability", col = "blue", main = "Profitability by Cluster")

#####
df_modified
barplot(AVG_NPV, names.arg = Cluster, xlab = "Cluster", ylab = "Average NPV", col = "red", main = "Average NPV by Cluster")

```


```{r, echo = TRUE}
####################
#7
df <- fread("Credit.csv")
df$AMOUNT_REQUESTED <- as.numeric(gsub(",","",df$AMOUNT_REQUESTED))
df$CREDIT_EXTENDED <- NULL
df$`OBS#` <- NULL
df$PROFITABLE <- ifelse(df$NPV > 0, 1, 0)
df$PROFITABLE <- factor(df$PROFITABLE)

#Creating Dummy Varaibles
df$CHK0 <- factor(ifelse(df$CHK_ACCT == 0, 1, 0))
df$CHK1 <- factor(ifelse(df$CHK_ACCT == 1, 1, 0))
df$CHK2 <- factor(ifelse(df$CHK_ACCT == 2, 1, 0))
df$CHK3 <- factor(ifelse(df$CHK_ACCT == 3, 1, 0))

df$SAV0 <- factor(ifelse(df$SAV_ACCT == 0, 1, 0))
df$SAV1 <- factor(ifelse(df$SAV_ACCT == 1, 1, 0))
df$SAV2 <- factor(ifelse(df$SAV_ACCT == 2, 1, 0))
df$SAV3 <- factor(ifelse(df$SAV_ACCT == 3, 1, 0))
df$SAV4 <- factor(ifelse(df$SAV_ACCT == 4, 1, 0))

df$HISTORY0 <- factor(ifelse(df$HISTORY == 0, 1, 0))
df$HISTORY1 <- factor(ifelse(df$HISTORY == 1, 1, 0))
df$HISTORY2 <- factor(ifelse(df$HISTORY == 2, 1, 0))
df$HISTORY3 <- factor(ifelse(df$HISTORY == 3, 1, 0))
df$HISTORY4 <- factor(ifelse(df$HISTORY == 4, 1, 0))

df$EMPLOYMENT0 <- factor(ifelse(df$EMPLOYMENT == 0, 1, 0))
df$EMPLOYMENT1 <- factor(ifelse(df$EMPLOYMENT == 1, 1, 0))
df$EMPLOYMENT2 <- factor(ifelse(df$EMPLOYMENT == 2, 1, 0))
df$EMPLOYMENT3 <- factor(ifelse(df$EMPLOYMENT == 3, 1, 0))
df$EMPLOYMENT4 <- factor(ifelse(df$EMPLOYMENT == 4, 1, 0))

df$OWN_RES <- factor(df$OWN_RES)

df$JOB0 <- factor(ifelse(df$JOB == 0, 1, 0))
df$JOB1 <- factor(ifelse(df$JOB == 1, 1, 0))
df$JOB2 <- factor(ifelse(df$JOB == 2, 1, 0))
df$JOB3 <- factor(ifelse(df$JOB == 3, 1, 0))

df$CHK_ACCT <- NULL
df$SAV_ACCT <- NULL
df$HISTORY <- NULL
df$EMPLOYMENT <- NULL
df$JOB <- NULL
df$NPV <- NULL

df <- df[, -(1:9)]
df <- df[, -(2:6)]

set.seed(12345)

rules <- apriori(df, parameter = list(supp = 0.1, conf = 0.8), 
                 appearance = list(rhs = "PROFITABLE=1"))

rules <- sort(rules, decreasing = TRUE, by = "lift")
inspect(rules[1:20])

```


```{r, echo = TRUE}
####################
#9
totalProfit = 0

df_new <- fread("Credit.csv")

for (i in 1:nrow(df_new)) {
  if(df[i]$CHK3 == 1 & df[i]$SAV1 == 0 & df[i]$HISTORY3 == 0 & df[i]$EMPLOYMENT0 == 0 & df[i]$EMPLOYMENT1 == 0 & df[i]$EMPLOYMENT2 == 0 & df[i]$JOB2 == 1)
    totalProfit = totalProfit + df_new[i]$NPV
}

totalProfit

avgProfit <- totalProfit/nrow(df_new)
avgProfit

```
